services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/ssl:/etc/ssl'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - qdrant
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - dev

networks:
  dev:

volumes:
  qdrant_data:
